spring:
  thymeleaf:
    mode: HTML
#连接数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root

##日志文件输出
logging:
  level:
    root: warn
    com.blog: trace
#  pattern:
#    console: %p%m%n




